### ISSUE TITLE
supporting the  `t.plan()` method

### ISSUE THREAD

**Issue by missinglink** [socketsupply/tapzero#14]
I find the `t.plan()` method from `node-tap` particularly useful, such as in situations like this where I want the test to fail if the callback is never called:

```js
test('something', t => {
  t.plan(1)

  events.on('message', (msg) => {
    t.equal(msg, 'hello')
  })
})
```

Would you be open to adding this to `tapzero`?
Is there a compelling reason it was not included, such as adding too much complexity to the code?
If not, would you be open to accepting a PR to add it?

> The function gets a Test object as its only argument. From there, you can call the t.end() method on that object to end the test, or use the t.plan() method to specify how many child tests or [asserts](https://node-tap.org/docs/api/asserts) the test will have.

https://node-tap.org/docs/api/#tplannumber
https://github.com/tapjs/libtap/blob/main/lib/test.js#L746

```bash
TypeError: t.plan is not a function
```

**Comment by jwerle** [comment]
@missinglink yeah I think that'll be useful. We can port to `socket:test` after we do it here
